# Generated by Django 4.0.5 on 2022-06-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0004_alter_musicinfo_music_aut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicinfo',
            name='music_titre',
            field=models.CharField(max_length=6),
        ),
    ]
