# Generated by Django 4.0.5 on 2022-06-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0006_alter_musicinfo_music_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicinfo',
            name='music_titre',
            field=models.CharField(max_length=60),
        ),
    ]
